import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertCircle, Beaker, BookOpen, CheckCircle2, Clock, FlaskConical } from "lucide-react";
import { SiteShell } from "@/components/site-shell";
import { experiments, titrationSteps } from "@/lib/experiments";

export const Route = createFileRoute("/tajribalar/$id")({
  head: () => ({ meta: [{ title: "Kislota–ishqor titrlash — TajribaLab" }, { name: "description", content: "Titrash tajribasining maqsadi, jihozlari va ilmiy modelini o‘rganing." }, { property: "og:title", content: "Kislota–ishqor titrlash — TajribaLab" }, { property: "og:description", content: "Virtual laboratoriyada titrlash tajribasini bajaring." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: Detail,
});
function Detail(){ const {id}=Route.useParams(); const experiment=experiments.find(x=>x.id===id); if(!experiment)return <SiteShell><main className="empty-state">Tajriba topilmadi.</main></SiteShell>; return <SiteShell><main><section className="detail-hero"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_360px]"><div><p className="eyebrow">Kimyo · Neytrallanish</p><h1 className="page-title">{experiment.title}</h1><p className="page-lead">Aniq hajmdagi kislota va ishqorni reaksiyaga kiritib, ekvivalent nuqtani indikator hamda pH orqali aniqlang.</p><div className="mt-6 flex flex-wrap gap-4 text-sm"><span className="detail-chip"><Clock size={17}/>{experiment.duration}</span><span className="detail-chip"><Beaker size={17}/>3D va 2D</span><span className="detail-chip"><BookOpen size={17}/>O‘rta daraja</span></div></div><div className="start-panel"><FlaskConical size={32}/><h2 className="font-display text-xl font-bold">Tajriba tayyor</h2><p className="text-sm text-muted-foreground">Ro‘yxatdan o‘tish shart emas. Natija shu qurilmada saqlanadi.</p><Link to="/lab/$id" params={{id}} className="btn-primary mt-4 w-full">Tajribani boshlash</Link></div></div></section><section className="mx-auto grid max-w-7xl gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_360px]"><div><h2 className="section-title">Tajriba bosqichlari</h2><ol className="mt-6 grid gap-3">{titrationSteps.map((step,i)=><li key={step} className="step-row"><span>{i+1}</span><p>{step}</p></li>)}</ol></div><aside><h2 className="section-title">Jihozlar</h2><ul className="info-list"><li>Byuretka va metall shtativ</li><li>Erlenmeyer kolbasi</li><li>25 ml o‘lchov pipetkasi</li><li>0,1 M HCl va 0,1 M NaOH</li><li>Fenolftalein indikatori</li></ul><div className="notice mt-6"><AlertCircle size={20}/><div><strong>Model chegarasi</strong><p>Ideal suyultirilgan eritmalar 25°C da hisoblanadi. Suyuqlik harakati soddalashtirilgan tasvir bilan ko‘rsatiladi.</p></div></div><div className="notice success mt-3"><CheckCircle2 size={20}/><div><strong>Xavfsiz virtual muhit</strong><p>Bu simulyatsiya real laboratoriyadagi himoya qoidalarini almashtirmaydi.</p></div></div></aside></section></main></SiteShell> }