import { useRef, useState } from 'react';
import { MolecularPreview } from './molecular-preview';
import type { MaterialId } from '@/lib/sandbox';
type Element = { n: number; symbol: string; name: string; mass: string; state: string; description: string; col: number; row: number; material?: MaterialId };
const featured: Element[] = [
  {n:1,symbol:'H',name:'Vodorod',mass:'1.008',state:'Gaz',description:'Yengil ikki atomli gaz — koinotda eng ko‘p tarqalgan element.',col:1,row:1,material:'hydrogen'},
  {n:26,symbol:'Fe',name:'Temir',mass:'55.845',state:'Qattiq',description:'Muhandislik va qurilishda ishlatiladigan keng tarqalgan o‘tish metali.',col:8,row:4,material:'iron'},
  {n:35,symbol:'Br',name:'Brom',mass:'79.904',state:'Suyuqlik',description:'Xona haroratida qizg‘ish-jigarrang galogen suyuqlik.',col:17,row:4,material:'bromine'},
];
const symbols = 'H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og'.split(' ');
function position(n:number):[number,number]{if(n<=2)return [n===1?1:18,1];if(n<=10)return [n<=4?n-2:n+8,2];if(n<=18)return [n<=12?n-10:n,3];if(n<=36)return [n-18,4];if(n<=54)return [n-36,5];if(n<=56)return [n-54,6];if(n<=71)return [n-54,9];if(n<=86)return [n-68,6];if(n<=88)return [n-86,7];if(n<=103)return [n-86,10];return [n-100,7];}
const cells: Element[] = symbols.map((symbol,i)=>{const n=i+1;const [col,row]=position(n);return featured.find(x=>x.n===n)??{n,symbol,name:symbol,mass:'—',state:'Ma’lumot uchun',description:'Faqat ma’lumot uchun joy egallovchi. Laboratoriya xatti-harakati hali qo‘shilmagan.',col,row};});
export function PeriodicTable({ onClose, onAdd }: { onClose:()=>void; onAdd:(id:MaterialId, origin:DOMRect)=>void }) {
 const [hovered,setHovered]=useState<Element|null>(null); const [anchor,setAnchor]=useState<DOMRect|null>(null); const hideTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const show=(el:Element,rect:DOMRect)=>{if(hideTimer.current)clearTimeout(hideTimer.current);setHovered(el);setAnchor(rect);};
 const hide=()=>{hideTimer.current=setTimeout(()=>setHovered(null),220);};
 const preview=hovered&&anchor; const left=anchor?Math.min(window.innerWidth-290,Math.max(12,anchor.left+anchor.width/2-140)):0; const top=anchor?Math.min(window.innerHeight-330,anchor.bottom+8):0;
 return <div className="periodic-overlay"><div className="periodic-head"><div><small>ELEMENTLARNI KO‘RISH</small><h2>Davriy jadval</h2><p>Ko‘rish uchun ustiga suring. H, Fe va Br laboratoriya uchun tayyor.</p></div><button onClick={onClose} aria-label="Davriy jadvalni yopish">✕</button></div><div className="periodic-scroll"><div className="periodic-grid">{cells.map(el=><button key={el.n} className={`element-tile ${el.material?'active':''} ${hovered?.n===el.n?'focused':''}`} style={{gridColumn:el.col,gridRow:el.row}} onMouseEnter={e=>show(el,e.currentTarget.getBoundingClientRect())} onMouseLeave={hide} onFocus={e=>show(el,e.currentTarget.getBoundingClientRect())} onClick={e=>el.material&&onAdd(el.material,e.currentTarget.getBoundingClientRect())}><small>{el.n}</small><strong>{el.symbol}</strong></button>)}</div></div>{preview&&<div className="element-preview" style={{left,top}} onMouseEnter={()=>{if(hideTimer.current)clearTimeout(hideTimer.current)}} onMouseLeave={hide}><div className="preview-top"><strong>{hovered.symbol}</strong><div><small>{hovered.n} · {hovered.mass} u</small><h3>{hovered.name}</h3><span>{hovered.state}</span></div></div>{hovered.material&&hovered.material!=='water'&&<><MolecularPreview type={hovered.material}/><small>{hovered.material==='iron'?'Atom / kristall tuzilishi':'Molekulyar tuzilishi'}</small></>}<p>{hovered.description}</p>{hovered.material&&<button onClick={()=>{onAdd(hovered.material!,anchor);onClose()}}>Laboratoriyaga qo‘shish ↗</button>}</div>}</div>;
}
